export const WEATHER_DATA = {
  regionCode: '02610114',
  largeAreaName: '경기도',
  middleAreaName: '광주시',
  smallAreaName: '고산동',
  observeYmdt: '20250104103817',
  detailUrl: 'https://weather.naver.com/today/02610114',
  displayTermType: 'HALF_DAY',
  announcement: '기상청',
  announcementUrl: 'https://www.weather.go.kr/w/index.do',
  shortTermForecasts: [
    {
      applyYmd: '20250104',
      applyHour: '10',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: -2,
      decimalTemperature: -2.3,
      compareTemperature: -1,
      stmpr: -2.3,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'S',
      windSpeed: 1.1,
      humidity: 57,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '11',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 0,
      decimalTemperature: 0,
      compareTemperature: 0.3,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'S',
      windSpeed: 0.8,
      humidity: 45,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '12',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 1,
      decimalTemperature: 1,
      compareTemperature: -0.2,
      stmpr: 1,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'SW',
      windSpeed: 0.9,
      humidity: 40,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '13',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 3,
      decimalTemperature: 3,
      compareTemperature: 0.6,
      stmpr: 2,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'W',
      windSpeed: 1.3,
      humidity: 35,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '14',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 5,
      decimalTemperature: 5,
      compareTemperature: 3,
      stmpr: 3.6,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'W',
      windSpeed: 1.8,
      humidity: 40,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '15',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 5,
      decimalTemperature: 5,
      compareTemperature: 3.7,
      stmpr: 3.7,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'W',
      windSpeed: 1.7,
      humidity: 40,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '16',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 4,
      decimalTemperature: 4,
      compareTemperature: 3,
      stmpr: 2.8,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'W',
      windSpeed: 1.5,
      humidity: 45,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '17',
      weatherCode: '1',
      weatherText: '맑음',
      temperature: 3,
      decimalTemperature: 3,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'W',
      windSpeed: 0.8,
      humidity: 55,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 0,
    },
    {
      applyYmd: '20250104',
      applyHour: '18',
      weatherCode: '6',
      weatherText: '구름많음',
      temperature: 1,
      decimalTemperature: 1,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'SW',
      windSpeed: 0.8,
      humidity: 65,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 20,
    },
    {
      applyYmd: '20250104',
      applyHour: '19',
      weatherCode: '6',
      weatherText: '구름많음',
      temperature: -1,
      decimalTemperature: -1,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'S',
      windSpeed: 0.7,
      humidity: 75,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 20,
    },
    {
      applyYmd: '20250104',
      applyHour: '20',
      weatherCode: '6',
      weatherText: '구름많음',
      temperature: -2,
      decimalTemperature: -2,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'SE',
      windSpeed: 0.9,
      humidity: 75,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 20,
    },
    {
      applyYmd: '20250104',
      applyHour: '21',
      weatherCode: '6',
      weatherText: '구름많음',
      temperature: -2,
      decimalTemperature: -2,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'SE',
      windSpeed: 1.2,
      humidity: 80,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 20,
    },
    {
      applyYmd: '20250104',
      applyHour: '22',
      weatherCode: '6',
      weatherText: '구름많음',
      temperature: -2,
      decimalTemperature: -2,
      compareTemperature: 0,
      stmpr: 0,
      oneHourRainAmt: 0,
      rainAmount: 0,
      windDirection: 'SE',
      windSpeed: 1.2,
      humidity: 80,
      detailUrl: 'https://weather.naver.com/today/02610114',
      rainProb: 20,
    },
  ],
  halfdayForecast: {
    applyYmd: '20250104',
    minTemperature: -6,
    amTemperature: -6,
    maxTemperature: 4,
    pmTemperature: 4,
    amWetrCd: '1',
    amWeatherCode: '1',
    pmWetrCd: '5',
    pmWeatherCode: '5',
    amWetrTxt: '맑음',
    amWeatherText: '맑음',
    pmWetrTxt: '구름많음',
    pmWeatherText: '구름많음',
    amWetrRainProb: 0,
    amRainProbability: 0,
    pmWetrRainProb: 20,
    pmRainProbability: 20,
    fcastYmdt: '20250104103817',
  },
  weeklyForecast: {
    regionCode: '02610114',
    largeAreaName: '경기도',
    middleAreaName: '광주시',
    smallAreaName: '고산동',
    observeYmdt: '20250104103817',
    dailyForecasts: [
      {
        applyYmd: '20250104',
        minTemperature: -6,
        amTemperature: -6,
        maxTemperature: 4,
        pmTemperature: 4,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '5',
        pmWeatherCode: '5',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '구름많음',
        pmWeatherText: '구름많음',
        amWetrRainProb: 0,
        amRainProbability: 0,
        pmWetrRainProb: 20,
        pmRainProbability: 20,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250105',
        minTemperature: -2,
        amTemperature: -2,
        maxTemperature: 4,
        pmTemperature: 4,
        amWetrCd: '14',
        amWeatherCode: '14',
        pmWetrCd: '14',
        pmWeatherCode: '14',
        amWetrTxt: '흐리고 한때 비/눈',
        amWeatherText: '흐리고 한때 비/눈',
        pmWetrTxt: '구름많고 비/눈',
        pmWeatherText: '구름많고 비/눈',
        amWetrRainProb: 80,
        amRainProbability: 80,
        pmWetrRainProb: 80,
        pmRainProbability: 80,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250106',
        minTemperature: -2,
        amTemperature: -2,
        maxTemperature: 4,
        pmTemperature: 4,
        amWetrCd: '7',
        amWeatherCode: '7',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '흐림',
        amWeatherText: '흐림',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 40,
        amRainProbability: 40,
        pmWetrRainProb: 0,
        pmRainProbability: 0,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250107',
        minTemperature: -7,
        amTemperature: -7,
        maxTemperature: -1,
        pmTemperature: -1,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '5',
        pmWeatherCode: '5',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '구름많음',
        pmWeatherText: '구름많음',
        amWetrRainProb: 0,
        amRainProbability: 0,
        pmWetrRainProb: 20,
        pmRainProbability: 20,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250108',
        minTemperature: -9,
        amTemperature: -9,
        maxTemperature: -2,
        pmTemperature: -2,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 10,
        amRainProbability: 10,
        pmWetrRainProb: 10,
        pmRainProbability: 10,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250109',
        minTemperature: -13,
        amTemperature: -13,
        maxTemperature: -4,
        pmTemperature: -4,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 10,
        amRainProbability: 10,
        pmWetrRainProb: 10,
        pmRainProbability: 10,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250110',
        minTemperature: -11,
        amTemperature: -11,
        maxTemperature: -2,
        pmTemperature: -2,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 10,
        amRainProbability: 10,
        pmWetrRainProb: 10,
        pmRainProbability: 10,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250111',
        minTemperature: -9,
        amTemperature: -9,
        maxTemperature: 1,
        pmTemperature: 1,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 10,
        amRainProbability: 10,
        pmWetrRainProb: 10,
        pmRainProbability: 10,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250112',
        minTemperature: -7,
        amTemperature: -7,
        maxTemperature: 1,
        pmTemperature: 1,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 20,
        amRainProbability: 20,
        pmWetrRainProb: 20,
        pmRainProbability: 20,
        fcastYmdt: '20250104103817',
      },
      {
        applyYmd: '20250113',
        minTemperature: -6,
        amTemperature: -6,
        maxTemperature: 2,
        pmTemperature: 2,
        amWetrCd: '1',
        amWeatherCode: '1',
        pmWetrCd: '1',
        pmWeatherCode: '1',
        amWetrTxt: '맑음',
        amWeatherText: '맑음',
        pmWetrTxt: '맑음',
        pmWeatherText: '맑음',
        amWetrRainProb: 20,
        amRainProbability: 20,
        pmWetrRainProb: 20,
        pmRainProbability: 20,
        fcastYmdt: '20250104103817',
      },
    ],
  },
  airForeCast: {
    fcastYmdt: '2025010409',
    stationId: null,
    stationName: '오포1동',
    stationType: null,
    stationAddr:
      '경기도 광주시 오포읍 오포로859번길 29 오포1동 행정복지센터 옥상',
    stationLat: 0,
    stationLng: 0,
    stationNaverRgnCd: '02610590',
    pm10: 40,
    pm10Legend: '보통',
    pm10LegendDesc: null,
    pm10ColorCode: '#39B74D',
    pm10TextColorCode: '#0D7A1F',
    pm25: 26,
    pm25Legend: '보통',
    pm25LegendDesc: null,
    pm25ColorCode: '#39B74D',
    pm25Exist: true,
    pm25TextColorCode: '#0D7A1F',
    o3: 0,
    o3Legend: null,
    o3ColorCode: null,
    o3LegendDesc: null,
    khai: 0,
    khaiLegend: null,
    khaiLegendDesc: null,
    khaiColorCode: null,
  },
  cachedTime: '2025-01-04 10:47:13',
  expiredTime: '2025-01-04 11:17:13',
}
